services:
  db:
    image: postgres:17
    container_name: TravelX-db
    environment:
      - POSTGRES_USER=grupo01
      - POSTGRES_PASSWORD=planetas01
      - POSTGRES_DB=planets_travel
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: TravelX-backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://grupo01:planetas01@db:5432/planets_travel
      - PORT=3000
    depends_on:
      - db
